name: Build C Program for Windows

on:
  push:
    branches:
      - main  # Trigger the workflow on 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on PRs to 'main'

jobs:
  build:
    runs-on: windows-latest  # Use the Windows runner to compile for Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-json-c
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-brotli
          mingw-w64-x86_64-libiconv
          mingw-w64-x86_64-nghttp2
          mingw-w64-x86_64-nghttp3
          mingw-w64-x86_64-ngtcp2
          mingw-w64-x86_64-libssh2
          mingw-w64-x86_64-libidn2
          mingw-w64-x86_64-libpsl
          mingw-w64-x86_64-winpthreads
          mingw-w64-x86_64-zstd

    - name: Build the program
      shell: msys2 {0}
      run: |
        mingw32-make -f Makefile  # Specify the Makefile explicitly

    - name: Copy required DLLs
      shell: msys2 {0}
      run: |
        # Core libraries
        cp /mingw64/bin/libcurl-4.dll .
        cp /mingw64/bin/zlib1.dll .
        cp /mingw64/bin/libjson-c-5.dll .
        cp /mingw64/bin/libssl-3-x64.dll .
        cp /mingw64/bin/libcrypto-3-x64.dll .
        # Brotli
        cp /mingw64/bin/libbrotlicommon.dll .
        cp /mingw64/bin/libbrotlienc.dll .
        cp /mingw64/bin/libbrotlidec.dll .
        # HTTP/2+ and QUIC deps
        cp /mingw64/bin/libnghttp2-14.dll .
        cp /mingw64/bin/libnghttp3-9.dll .
        cp /mingw64/bin/libngtcp2-16.dll .
        cp /mingw64/bin/libngtcp2_crypto_ossl.dll .
        # SSH and other curl deps
        cp /mingw64/bin/libssh2-1.dll .
        cp /mingw64/bin/libidn2-0.dll .
        cp /mingw64/bin/libpsl-5.dll .
        cp /mingw64/bin/libiconv-2.dll .
        # Compression
        cp /mingw64/bin/libzstd.dll .
        # Runtime and threading
        cp /mingw64/bin/libgcc_s_seh-1.dll .
        cp /mingw64/bin/libwinpthread-1.dll .

        # Copy CA certificate bundle
        cp cacert.pem .

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Upload the artifact
      with:
        name: bit-windows
        path: .