name: Build C Program for Windows with MSYS2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MSYS2
      run: |
        choco install msys2
        refreshenv

    - name: Set MSYS2 environment
      run: |
        echo "C:\\tools\\msys64\\usr\\bin" >> $GITHUB_ENV  # Add MSYS2 bin directory to PATH

    - name: Update MSYS2
      run: |
        C:\\tools\\msys64\\usr\\bin\\bash.exe -c "pacman -Syu --noconfirm"

    - name: Install dependencies
      run: |
        C:\\tools\\msys64\\usr\\bin\\bash.exe -c "pacman -S --noconfirm mingw-w64-x86_64-gcc make"

    - name: Build the C program
      run: |
        C:\\tools\\msys64\\usr\\bin\\bash.exe -c "make Bit.exe"

    - name: Upload Windows executable
      uses: actions/upload-artifact@v2
      with:
        name: bit-executable
        path: Bit.exe
